// This file is generated by Convex
// When generateCommonJSApi is true, Convex generates this file
// For now, this is a stub that exports the api object structure
// In production, this will be generated by `npx convex codegen`

// The actual api object is provided by the Convex runtime
// This stub ensures webpack can resolve the import
export const api = {};

