// This file is auto-generated by Convex
// When generateCommonJSApi is true, Convex generates this file
// This is a stub for build-time. In production, run `npx convex codegen` to generate the real file.

// Stub API object structure matching the Convex generated API
export const api = {
  attachments: {},
  memory: {},
  messages: {},
  presence: {},
  provider: {},
  rooms: {},
  schema: {},
  settings: {},
  threads: {},
  users: {},
};
